### PR TITLE
(SIMP-4009) Add support for OEL and Puppet 5

### PR DESCRIPTION
**Pull request by trevor-vaughan**
Requires updates to auditd and iptables

SIMP-4009 #comment updated rsyslog

### CODE REVIEW

**Comment by ayohrling** [comment]
I'm going to add my review as positive; since the acceptance tests all ran properly locally and tests are passing and code looks good. But I did update some things regarding the acceptance so likely someone else should review this as well.

**Comment by trevor-vaughan** [comment]
@ayohrling Those changes look good to me since they're based off of the new work. If you're happy with what I've done, and this is all you're updating, feel free to go ahead and merge.

You should be able to rebase as well and force push. If you need me to do it, let me know.

**Comment by jeefberkey** [comment]
:clock4: https://gitlab.com/simp/pupmod-simp-rsyslog/pipelines/24397444

**Comment by jeefberkey** [comment]
https://gitlab.com/simp/pupmod-simp-rsyslog/pipelines/25721179

**Pull request merged**
