### PR TITLE
(SIMP-8958) Standardize assets in pupmod-simp-rsyslog

### PR DESCRIPTION
**Pull request by op-ct**
This patch baselines the latest standardized assets for Puppet modules.

SIMP-9067 #close
[SIMP-8958] #comment Standardized assets in pupmod-simp-rsyslog
[SIMP-8489] #comment Updated pupmod-simp-rsyslog GLCI pipeline to Puppet 6.18
[SIMP-8923] #comment Renamed 'sanity' to 'releng' in pupmod-simp-rsyslog
[SIMP-8984] #comment Updated pupmod-simp-rsyslog to new GLCI conventions

[SIMP-8958]: https://simp-project.atlassian.net/browse/SIMP-8958
[SIMP-8489]: https://simp-project.atlassian.net/browse/SIMP-8489
[SIMP-8923]: https://simp-project.atlassian.net/browse/SIMP-8923
[SIMP-8984]: https://simp-project.atlassian.net/browse/SIMP-8984

### CODE REVIEW

**Comment by op-ct** [comment]
I removed some obvious EL6/rsyslog7 things, but I'd appreciate some help with rooting the rest out from someone who is more familiar with this module's handling of el6/rsyslog7 details.

**Comment by lnemsick-simp** [comment]
I'll take a look at the EL6 removal in more detail

**Comment by lnemsick-simp** [comment]
I recommend having this PR only remove EL6 from the testing, and have a separate PR to update the module for support of Rsyslog 8, only, for EL7 and EL8.  I will back out the partial code changes.

**Review by lnemsick-simp — APPROVED** [review]

**Comment by lnemsick-simp** [comment]
Acceptance test problems are unrelated to this PR and have been noted in https://simp-project.atlassian.net/browse/SIMP-9147

**Pull request merged**
